services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: todo_list
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
